#! /usr/bin/env ruby
# coding: utf-8

require 'pathname'
require 'optparse'
require 'yaml'
require 'securerandom'
require 'sqlite3'

BASE_DIR    = Pathname.new(File.expand_path(__FILE__)).dirname.parent.parent
DATA_DIR    = BASE_DIR + "data"
LIB_DIR     = BASE_DIR + "lib" + "envlog"
SCHEMA_FILE = DATA_DIR + "schema.yml"

require "#{LIB_DIR + "version"}"
require "#{LIB_DIR + "misc"}"
require "#{LIB_DIR + "schema"}"
require "#{LIB_DIR + "config"}"

OptionParser.new { |opt|
  opt.version = EnvLog::VERSION
  opt.banner += " BT-ADDR DESCRIPTION POWER-SOURCE"

  opt.on("-c FILE", "--config-file=FILE") { |file|
    $config_file = file
  }

  opt.parse!(ARGV)

  raise("configuration file is not specified.") if not $config_file
}

EnvLog::Schema.read(SCHEMA_FILE)
EnvLog::Config.read($config_file)

raise("arguments not enough") if ARGV.size < 3

addr  = ARGV[0]
descr = ARGV[1]
psrc  = ARGV[2]

if EnvLog::Config.has?(:database, :sqlite3)
  db_path = EnvLog::Config.fetch_path(:database, :sqlite3, :path)
else
  raise("SQLite3 configuration is not specified")
end

begin
  db = SQLite3::Database.new(db_path.to_s)

  db.transaction

  row = db.get_first_row(<<~EOQ, addr)
    select id, state from SENSOR_TABLE where addr = ?;
  EOQ

  if not row
    #
    # 新規登録の場合
    #
    id = SecureRandom.uuid

    db.execute2(<<~EOQ, addr, id, descr, psrc)
      insert into SENSOR_TABLE
          values (?,
                  ?,
                  datetime('now', 'localtime'),
                  datetime('now', 'localtime'),
                  ?,
                  ?,
                  "READY",
                  NULL);
    EOQ

  else
    id = row[0]
    st = row[1]

    if st == "UNKNOWN"
      #
      # 不明デバイスもしくとして既に登録されていた場合
      #
      db.execute2(<<~EOQ, descr, psrc, id)
        update SENSOR_TABLE
            set mtime        = datetime('now', 'localtime'),
                descr        = ?,
                `pow-source` = ?,
                state        = "READY",
                `last-seq`   = NULL
            where id = ?;
      EOQ
    else
      raise("device #{addr} is working now")
    end
  end

  db.commit

rescue => e
  STDERR.print(e.message)
  #pp backtrace
  db.rollback

ensure
  db&.close
end
