#! /usr/bin/env ruby
# coding: utf-8

#
# Environemnt data logger
#
#   Copyright (C) 2020 Hiroshi Kuwagata <kgt9221@gmail.com>
#

require 'pathname'
require 'optparse'
require 'yaml'

BASE_DIR = Pathname.new(File.expand_path(__FILE__)).dirname.parent.parent
DATA_DIR = BASE_DIR + "data"
LIB_DIR  = BASE_DIR + "lib" + "envlog"

require "#{LIB_DIR + "version"}"
require "#{LIB_DIR + "misc"}"
require "#{LIB_DIR + "schema"}"
require "#{LIB_DIR + "config"}"

OptionParser.new { |opt|
  opt.version = EnvLog::VERSION

  opt.on("-c FILE", "--config-file=FILE") { |file|
    $config_file = file
  }

  opt.parse!(ARGV)

  raise("configuration file is not specified.") if not $config_file
}

SCHEMA = EnvLog::Schema.read(DATA_DIR + "schema.yml")
CONFIG = EnvLog::Config.read($config_file)

if CONFIG["database"].include?("mysql")
	host = CONFIG.dig("database", "mysql", "host")
	user = CONFIG.dig("database", "mysql", "username")
	pass = CONFIG.dig("database", "mysql", "password")
	db   = CONFIG.dig("database", "mysql", "database")

	system(%Q{mysql -h"#{host}" -u"#{user}" -p"#{pass}" "#{db}"})
else
	raise("MySQL configuration is not specified")
end
