#! /usr/bin/env ruby
# coding: utf-8

#
# Environemnt data logger
#
#   Copyright (C) 2020 Hiroshi Kuwagata <kgt9221@gmail.com>
#

require 'pathname'
require 'optparse'
require 'yaml'

BASE_DIR    = Pathname.new(File.expand_path(__FILE__)).dirname.parent
DATA_DIR    = BASE_DIR + "data"
LIB_DIR     = BASE_DIR + "lib" + "envlog"
SCHEMA_FILE = DATA_DIR + "schema.yml"

require "#{LIB_DIR + "version"}"
require "#{LIB_DIR + "misc"}"
require "#{LIB_DIR + "schema"}"
require "#{LIB_DIR + "config"}"

OptionParser.new { |opt|
  opt.version = EnvLog::VERSION

  opt.on("-c FILE", "--config-file=FILE") { |file|
    $config_file = file
  }

  opt.parse!(ARGV)

  raise("configuration file is not specified.") if not $config_file
}

EnvLog::Schema.read(SCHEMA_FILE)
EnvLog::Config.read($config_file)

case
when EnvLog::Config.has?(:database, :sqlite3)
  db_path = EnvLog::Config.fetch_path(:database, :sqlite3, :path)

  system(%Q{sqlite3 "#{db_path}"})

when EnvLog::Config.has?(:database, :mysql)
	host = EnvLog::Config.dig(:database, :mysql, :host)
	user = EnvLog::Config.dig(:database, :mysql, :username)
	pass = EnvLog::Config.dig(:database, :mysql, :password)
	db   = EnvLog::Config.dig(:database, :mysql, :database)

	system(%Q{mysql -h"#{host}" -u"#{user}" -p"#{pass}" "#{db}"})

else
  raise("really?")
end
